cargo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import home_page, RouteListView, RouteCreateView, RouteEditView, RouteDeleteView, DriverCreateView, DriverEditView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page, name='home'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^acconts/', include('allauth.urls')),
    url(r'^routes/$', RouteListView.as_view(), name='route_list'),
    url(r'^route/create/$', RouteCreateView.as_view(), name='route_create'),
    url(r'^route/(?P<pk>\d+)/update/$', RouteEditView.as_view(), name='route_update'),
    url(r'^route/(?P<pk>\d+)/delete/$', RouteDeleteView.as_view(), name='route_delete'),
    url(r'^driver/create/$', DriverCreateView.as_view(), name='driver_create'),
    url(r'^driver/(?P<pk>\d+)/update/$', DriverEditView.as_view(), name='driver_update')
]

cargo/models.py
from django.db import models


class RouteStatus(models.Model):
    status = models.CharField(max_length=20)

    def __str__(self):
        return '{}'.format(self.status)


class Driver(models.Model):
    name = models.TextField(default='')
    phone = models.TextField(default='')

    def __str__(self):
        return '{}({})'.format(self.name, self.phone)


class Route(models.Model):
    driver = models.ForeignKey(Driver, on_delete=models.CASCADE, null=True)
    status = models.ForeignKey(RouteStatus, on_delete=models.CASCADE, null=True)
    route = models.TextField(default='')
    gate = models.TextField(null=True)

cargo/forms.py
from django import forms
from .models import Route, RouteStatus, Driver


class CreateRouteForm(forms.ModelForm):
    class Meta(object):
        model = Route
        fields = ['route', 'driver', 'status', 'gate']

    driver = forms.ModelChoiceField(queryset=Driver.objects.all())
    route = forms.CharField(label='Route', max_length=100)
    gate = forms.CharField(label='Gate', max_length=100, required=False)
    status = forms.ModelChoiceField(queryset=RouteStatus.objects.all())


class EditRouteForm(forms.ModelForm):
    class Meta(object):
        model = Route
        fields = ['route', 'driver', 'status', 'gate']

    driver = forms.ModelChoiceField(queryset=Driver.objects.all())
    route = forms.CharField(label='Route', max_length=100)
    gate = forms.CharField(label='Gate', max_length=100, required=False)
    status = forms.ModelChoiceField(queryset=RouteStatus.objects.all())


class DriverCreateForm(forms.ModelForm):
    class Meta(object):
        model = Driver
        fields = ['name', 'phone']

    name = forms.CharField(max_length=100)
    phone = forms.CharField(max_length=100)


class DriverEditForm(forms.ModelForm):
    class Meta(object):
        model = Driver
        fields = ['name', 'phone']

    name = forms.CharField(max_length=100)
    phone = forms.CharField(max_length=100)

cargo/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Route, Driver
from .forms import CreateRouteForm, EditRouteForm, DriverCreateForm, DriverEditForm
from django.contrib.auth.decorators import login_required


class RouteListView(ListView):
    model = Route
    context_object_name = 'route_list'
    template_name = 'route_list.html'

    def get_queryset(self):
        return super(RouteListView, self).get_queryset()


class RouteCreateView(CreateView):
    template_name = 'route_create.html'
    form_class = CreateRouteForm
    success_url = '/routes/'


class RouteEditView(UpdateView):
    model = Route
    form_class = EditRouteForm
    template_name = 'route_edit.html'
    success_url = '/routes/'


class RouteDeleteView(DeleteView):
    model = Route
    template_name = 'route_delete.html'
    success_url = '/routes/'


class DriverCreateView(CreateView):
    model = Driver
    form_class = DriverCreateForm
    template_name = 'driver_create.html'

    def get_success_url(self):
        return '/route/create/'


class DriverEditView(UpdateView):
    model = Driver
    form_class = DriverEditForm
    template_name = 'driver_edit.html'
    success_url = '/routes/'


@login_required
def home_page(request):
    if request.method == 'POST':
        Route.objects.create(driver=request.POST['driver'])
        return redirect('/')

    routes = Route.objects.all()
    return render(request, 'home.html', {'routes': routes})

cargo/templates/base.html
{% load staticfiles %}
<html>
<head>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
</head>
<body>
    <div class="content container">
        <div class="row">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    {% block login %}
    {% endblock %}
</body>
</html>

cargo/templates/driver_create.html
<!DOCTYPE html>
<html lang="en">
    <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">

         <!-- Website CSS style -->
		<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">

		<!-- Website Font style -->
	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
        <link href="/static/bootstrap/css/base_form.css" rel="stylesheet" media="screen">
        <!-- Google Fonts -->
		<link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<div class="container">
			<div class="row main">
				<div class="main-login main-center">
					<form class="" method="post" action="">{% csrf_token %}

						<div class="form-group">
							<label for="name" class="cols-sm-2 control-label">Водитель</label>
                            <span style="color:red">{{ form.name.errors }}</span>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-hand-o-right fa" aria-hidden="true"></i></span>
									<input type="text" class="form-control" name="name" id="name"  placeholder="Фамилия Имя"/>
                                </div>
							</div>
						</div>

                        <div class="form-group">
							<label for="name" class="cols-sm-2 control-label">Телефон</label>
                            <span style="color:red">{{ form.phone.errors }}</span>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-hand-o-right fa" aria-hidden="true"></i></span>
									<input type="text" class="form-control" name="phone" id="phone"  placeholder="Номер телефона"/>
                                </div>
							</div>
						</div>

                        <input type="hidden" name="redirect_url" value="{{ request.next }}" />

                        <div class="form-group ">
						    <input class="btn btn-primary btn-lg btn-block login-button" type="submit" value="Сохранить" />
                        </div>

					</form>
				</div>
			</div>
		</div>

		 <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
	</body>
</html>

cargo/templates/driver_edit.html
<!DOCTYPE html>
<html lang="en">
    <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">

         <!-- Website CSS style -->
		<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">

		<!-- Website Font style -->
	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
        <link href="/static/bootstrap/css/base_form.css" rel="stylesheet" media="screen">
        <!-- Google Fonts -->
		<link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<div class="container">
			<div class="row main">
				<div class="main-login main-center">
					<form class="" method="post" action="">{% csrf_token %}

						<div class="form-group">
							<label for="name" class="cols-sm-2 control-label">Водитель</label>
                            <span style="color:red">{{ form.name.errors }}</span>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-hand-o-right fa" aria-hidden="true"></i></span>
									<input type="text" class="form-control" name="name" id="name"  placeholder="Фамилия Имя" value="{{ driver.name }}" />
                                </div>
							</div>
						</div>

                        <div class="form-group">
							<label for="name" class="cols-sm-2 control-label">Телефон</label>
                            <span style="color:red">{{ form.phone.errors }}</span>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-hand-o-right fa" aria-hidden="true"></i></span>
									<input type="text" class="form-control" name="phone" id="phone"  placeholder="Номер телефона" value="{{ driver.phone }}" />
                                </div>
							</div>
						</div>

                        <input type="hidden" name="redirect_url" value="{{ request.next }}" />

                        <div class="form-group ">
						    <input class="btn btn-primary btn-lg btn-block login-button" type="submit" value="Редактировать" />
                        </div>

					</form>
				</div>
			</div>
		</div>

		 <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
	</body>
</html>

cargo/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>GARGO</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/base.css" rel="stylesheet">
</head>
<body>
  <div class="container">

    <div class="row">
        <div class="col-md-6 col-md-offset-3 jumbotron">
            <div class="text-center">
                <h1>Routes List</h1>
                <form method="POST">
                    <input name="driver" id="id_new_driver" class="form-control input-lg" placeholder="Enter a driver" />
                    {% csrf_token %}
                </form>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <table id="id_route_table" class="table">
                {% for route in routes %}
                    <tr><td>{{ route.driver.name }}</td><td>{{ route.route }}</td></tr>
                {% endfor %}
            </table>
        </div>
    </div>

  </div>
</body>

cargo/templates/route_create.html
<!DOCTYPE html>
<html lang="en">
    <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">

         <!-- Website CSS style -->
		<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">

		<!-- Website Font style -->
	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
        <link href="/static/bootstrap/css/base_form.css" rel="stylesheet" media="screen">
        <!-- Google Fonts -->
		<link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<div class="container">
			<div class="row main">
				<div class="main-login main-center">
                    <h5>Заполните форму регистрации машрута.</h5>
					<form class="" method="post" action="">{% csrf_token %}

						<div class="form-group">
							<label for="name" class="cols-sm-2 control-label">Машрут</label>
                            <span style="color:red">{{ form.route.errors }}</span>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-hand-o-right fa" aria-hidden="true"></i></span>
									<input type="text" class="form-control" name="route" id="route"  placeholder="Введите машрут"/>
                                </div>
							</div>
						</div>

						<div class="form-group">
                            <label for="driver" class="cols-sm-2 control-label">Водитель</label>
                            <span style="color:red">{{ form.driver.errors }}</span>
                            <select class="select form-control" id="id_driver" name="driver">
                            {% for id, driver in form.driver.field.choices %}
                                <option value="{{ id }}"
                                    {% if form.driver.value == id %}
                                        selected="selected"
                                     {% endif %}>
                                        {{ driver }}
                                    </option>
                            {% endfor %}
                            </select>
                            <div class="row">
                                    <div style="height:0.5em"></div>
                                    <div class="col-md-offset-1">
                                        <a id='create_driver' href="/driver/create"><span style="color:white" class="glyphicon glyphicon-plus-sign"></span></a>
                                    </div>
                            </div>
                        </div>

                        <div class="form-group">
							<label for="satus" class="cols-sm-2 control-label">Статус</label>
							<span style="color:red">{{ form.status.errors }}</span>
                            <select class="select form-control" id="id_status" name="status">
                            {% for id, name in form.status.field.choices %}
                                <option value="{{ id }}"
                                    {% if form.status.value == id %}
                                        selected="selected"
                                     {% endif %}>{{ name }}
                                    </option>
                            {% endfor %}
                            </select>
                        </div>

						<div class="form-group">
							<label for="gate" class="cols-sm-2 control-label">Ворота</label>
                            <span style="color:red">{{ form.gate.errors }}</span>
                            <div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-calendar-plus-o" aria-hidden="true"></i></span>
									<input type="text" class="form-control" name="gate" id="gate"  placeholder="Введите номер ворот"/>
								</div>
							</div>
						</div>

                        {% if redirect_field_value %}
                            <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                        {% endif %}

                        <div class="form-group ">
						    <input class="btn btn-primary btn-lg btn-block login-button" type="submit" value="Сохранить" />
                        </div>

					</form>
				</div>
			</div>
		</div>

		 <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
	</body>
</html>

cargo/templates/route_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object.id }}"?</p>
    <input type="submit" value="Confirm" />
</form>

cargo/templates/route_edit.html
<!DOCTYPE html>
<html lang="en">
    <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">

         <!-- Website CSS style -->
		<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">

		<!-- Website Font style -->
	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
        <link href="/static/bootstrap/css/base_form.css" rel="stylesheet" media="screen">
        <!-- Google Fonts -->
		<link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<div class="container">
			<div class="row main">
				<div class="main-login main-center">
                    <h5>Заполните форму регистрации машрута.</h5>
					<form class="" method="post" action="">{% csrf_token %}

						<div class="form-group">
							<label for="name" class="cols-sm-2 control-label">Машрут</label>
                            <span style="color:red">{{ form.route.errors }}</span>
                            <div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-hand-o-right fa" aria-hidden="true"></i></span>
									<input type="text" class="form-control" name="route" id="route"  placeholder="Введите машрут" value="{{ route.route }}"/>
                                </div>
							</div>
						</div>

						<div class="form-group">
                            <label for="driver" class="cols-sm-2 control-label">Водитель</label>
                            <span style="color:red">{{ form.driver.errors }}</span>
                            <select class="select form-control" id="id_driver" name="driver">
                            {% for id, driver in form.driver.field.choices %}
                                <option value="{{ id }}"
                                    {% if form.driver.value == id %}
                                        selected="selected"
                                     {% endif %}>
                                        {{ driver }}
                                    </option>
                            {% endfor %}
                            </select>
                        </div>

						<div class="form-group">
							<label for="password" class="cols-sm-2 control-label">Статус</label>
							<span style="color:red">{{ form.status.errors }}</span>
                            <select class="select form-control" id="id_status" name="status">
                            {% for id, name in form.status.field.choices %}
                                <option value="{{ id }}"
                                    {% if form.status.value == id %}
                                        selected="selected"
                                     {% endif %}>{{ name }}
                                    </option>
                            {% endfor %}
                            </select>
                        </div>

						<div class="form-group">
							<label for="confirm" class="cols-sm-2 control-label">Ворота</label>
                            <div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-calendar-plus-o" aria-hidden="true"></i></span>
									<input type="text" class="form-control" name="gate" id="gate"  placeholder="Введите номер ворот" value="{{ route.gate |default_if_none:""}}"/>
								</div>
							</div>
						</div>

                        {% if redirect_field_value %}
                            <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                        {% endif %}

                        <div class="form-group ">
						    <input class="btn btn-primary btn-lg btn-block login-button" type="submit" value="Редактировать" />
                        </div>

					</form>
				</div>
			</div>
		</div>

		 <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
	</body>
</html>

cargo/templates/route_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="text-center">
        <h2>Маршрутный лист</h2>
    </div>
    <table class="table table-striped">
        <tr>
            <th>Маршрут</th>
            <th>Водитель</th>
            <th>&nbsp;</th>
            <th>Телефон</th>
            <th>Статус</th>
            <th>Ворота</th>
            <th>Редактировать</th>
            <th>Удалить</th>
        </tr>
        {% for route in object_list %}
            <tr><td>{{ route.route }}</td>
                <td>{{ route.driver.name }}</td>
                <td class="driver_update"><a href="/driver/{{ route.driver.id }}/update/"><span class="glyphicon glyphicon-pencil"></span></a></td>
                <td>{{ route.driver.phone }}</td>
                <td>{{ route.status.status }}</td>
                <td>{{ route.gate|default_if_none:"" }}</td>
                <td class="route_update" id="update-{{ route.id }}"><a href="/route/{{ route.id }}/update/"><span class="glyphicon glyphicon-pencil"></span></a></td>
                <td class="route_delete" id="delete-{{ route.id }}"><a href="/route/{{ route.id }}/delete/"><span class="glyphicon glyphicon-trash"></span></a></td>
            </tr>
        {% endfor %}
    </table>

    <a href="/route/create/" class="btn btn-info" role="button">Добавить Маршрут</a>

{% endblock %}